metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  ci:
    envs:
      host:
        args: []
    path: ci/
    stages:
    - test-generate
search_sources:
- popperized
version: 1
